name: Travis Neilson
description: travis writes and designs things that matter to him.
url: http://travisneilson.com

permalink: /:title/

exclude:  [
  'style.sass',
  'README.md',
  '.gitignore'  
]

port: 8000

sass:
    sass_dir: assets/css

collections:
  notes:
    output: true
